### ISSUE TITLE
Q2-ITSxpress: File too small?

### ISSUE THREAD

**Issue by brittonstrickland** [USDA-ARS-GBRU/itsxpress#22]
Hi all,

I am using the Qiime2 plugin of ITSxpress to do some fungal seq analysis. I've used this plugin previously without any issue. I am running Qiime2-2021.8 and ITSxpress v1.8.0 (both Conda and pip installation methods). I first imported my demultiplexed data then proceeded directly to ITSxpress with the command:

`qiime itsxpress trim-pair-output-unmerged \
	--i-per-sample-sequences 1_0_input_seqs.qza \
	--p-region ITS1 \
	--p-taxa F \
	--p-threads 8 \
	--o-trimmed 1_1_pair_trimmed_itsxpress.qza \
        --verbose`

It runs for a while, but gives me the error: 

```
Plugin error from itsxpress:

  Command '['vsearch', '--cluster_size', '/var/folders/q4/1wyb8l014g5bzmrvwg77plz00000gp/T/itsxpress_s74av6rt/seq.fq.gz', '--centroids', '/var/folders/q4/1wyb8l014g5bzmrvwg77plz00000gp/T/itsxpress_s74av6rt/rep.fa', '--uc', '/var/folders/q4/1wyb8l014g5bzmrvwg77plz00000gp/T/itsxpress_s74av6rt/uc.txt', '--strand', 'both', '--id', '0.995', '--threads', '8']' returned non-zero exit status 1.

See above for debug info.
```

For more debug info:
```

...
...
Reading file /var/folders/q4/1wyb8l014g5bzmrvwg77plz00000gp/T/itsxpress_zk_pqxzy/seq.fq.gz 100%
9641893 nt in 35445 seqs, min 68, max 491, avg 272
Masking 100%
Sorting by abundance 100%
Counting k-mers 100%
Clustering 100%
Sorting clusters 100%
Writing clusters 100%
Clusters: 6883 Size min 1, max 14632, avg 5.1
Singletons: 4514, 12.7% of seqs, 65.6% of clusters

vsearch v2.7.0_macos_x86_64, 16.0GB RAM, 8 cores
https://github.com/torognes/vsearch



Fatal error: File too small

ERROR:root:Could not perform clustering with Vsearch. Error from Vsearch was:
 vsearch v2.7.0_macos_x86_64, 16.0GB RAM, 8 cores
https://github.com/torognes/vsearch



Fatal error: File too small
Traceback (most recent call last):
  File "/Users/stricba1/opt/anaconda3/envs/qiime2-2021.8/lib/python3.8/site-packages/itsxpress/main.py", line 540, in cluster
    p2.check_returncode()
  File "/Users/stricba1/opt/anaconda3/envs/qiime2-2021.8/lib/python3.8/subprocess.py", line 448, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['vsearch', '--cluster_size', '/var/folders/q4/1wyb8l014g5bzmrvwg77plz00000gp/T/itsxpress_s74av6rt/seq.fq.gz', '--centroids', '/var/folders/q4/1wyb8l014g5bzmrvwg77plz00000gp/T/itsxpress_s74av6rt/rep.fa', '--uc', '/var/folders/q4/1wyb8l014g5bzmrvwg77plz00000gp/T/itsxpress_s74av6rt/uc.txt', '--strand', 'both', '--id', '0.995', '--threads', '8']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/Users/stricba1/opt/anaconda3/envs/qiime2-2021.8/lib/python3.8/site-packages/q2cli/commands.py", line 329, in __call__
    results = action(**arguments)
  File "<decorator-gen-287>", line 2, in trim_pair_output_unmerged
  File "/Users/stricba1/opt/anaconda3/envs/qiime2-2021.8/lib/python3.8/site-packages/qiime2/sdk/action.py", line 245, in bound_callable
    outputs = self._callable_executor_(scope, callable_args,
  File "/Users/stricba1/opt/anaconda3/envs/qiime2-2021.8/lib/python3.8/site-packages/qiime2/sdk/action.py", line 391, in _callable_executor_
    output_views = self._callable(**view_args)
  File "/Users/stricba1/opt/anaconda3/envs/qiime2-2021.8/lib/python3.8/site-packages/q2_itsxpress/_itsxpress.py", line 151, in trim_pair_output_unmerged
    results = main(per_sample_sequences=per_sample_sequences,
  File "/Users/stricba1/opt/anaconda3/envs/qiime2-2021.8/lib/python3.8/site-packages/q2_itsxpress/_itsxpress.py", line 208, in main
    sobj.cluster(threads=threads, cluster_id=cluster_id)
  File "/Users/stricba1/opt/anaconda3/envs/qiime2-2021.8/lib/python3.8/site-packages/itsxpress/main.py", line 543, in cluster
    raise e
  File "/Users/stricba1/opt/anaconda3/envs/qiime2-2021.8/lib/python3.8/site-packages/itsxpress/main.py", line 540, in cluster
    p2.check_returncode()
  File "/Users/stricba1/opt/anaconda3/envs/qiime2-2021.8/lib/python3.8/subprocess.py", line 448, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['vsearch', '--cluster_size', '/var/folders/q4/1wyb8l014g5bzmrvwg77plz00000gp/T/itsxpress_s74av6rt/seq.fq.gz', '--centroids', '/var/folders/q4/1wyb8l014g5bzmrvwg77plz00000gp/T/itsxpress_s74av6rt/rep.fa', '--uc', '/var/folders/q4/1wyb8l014g5bzmrvwg77plz00000gp/T/itsxpress_s74av6rt/uc.txt', '--strand', 'both', '--id', '0.995', '--threads', '8']' returned non-zero exit status 1.
```

I've seen a couple of issues relating to this bug, and I've initiated a pre-import sequence cutoff of 200, 500, 1000, 5000 and still getting the same error. I must have a bad file somewhere that I cannot find. The new version of Vsearch now flags this issue as a warning, not something that will kill the program. (see https://github.com/torognes/vsearch/issues/366)

Again, I've seen this issue come up a few times, and I cannot seem to find a solution. Any help would be appreciated!

**Comment by arivers** [comment]
resolved in newer versions.
